[package]
name = "flt-cli"
version = "0.1.0"
edition = "2021"
default-run = "flt-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
fs_extra = "1.3.0"
